FROM woshicheng93632/centos7sshjdk8
MAINTAINER chenjianfan（316031139@qq.com）
#把java 加入容器中  
Add  hadoop-3.1.1.tar.gz    /usr/local/
#配置java 环境变量  
ENV HADOOP_HOME /usr/local/hadoop-3.1.1
ENV PATH $PATH:$HADOOP_HOME/bin:$HADOOP_HOME/sbin

